#!/usr/bin/env bash

echo "Installing CTDYN..."

if [ -z "$CTDYN_DIR" ]
then
	echo
	echo "****************************************************************"
	echo "*                                                              *"
	echo "*                      CTDYN_DIR is not set                    *"
	echo "*            Please set CTDYN_DIR and run ./install            *"
	echo "*                                                              *"
	echo "****************************************************************"
	echo
	exit 1
fi

export USE_MESASDK=0
export USE_DEFAULT_EXTERNAL=0
# Input option
# -b : build choice, debug or release
# -v, -V : verbosity levels
# -e : set to use LAPACK library from MESASDK
# -d : set to use default external LAPACK library
while getopts "b:vedV" opt; do
  case $opt in
    b) BUILD_OPTION="$OPTARG"
    ;;
    v) VERB_OPTION=1
    ;;
    V) VERB_OPTION=2
    ;;
    e) export USE_MESASDK=1
    ;;
    d) export USE_DEFAULT_EXTERNAL=1
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $opt needs a valid argument"
    exit 1
    ;;
  esac
done

# Setting and checking build options
if [ "$BUILD_OPTION" = "" ]
then
	BUILD_OPTION="release"
fi

# Default verbose options
if [ "$VERB_OPTION" = "" ]
then
	VERB_OPTION=0
fi

# Creating the binary directory
BINARY_DIR="bin"
if [ ! -d $BINARY_DIR ]
then
	mkdir $BINARY_DIR
fi

cd $BINARY_DIR
EXECUTABLE="ctdyn"

# Cleaning any existing executable
if [ -f $EXECUTABLE ]
then
	rm $EXECUTABLE
        echo "Found and deleted existing executable."
fi


if [ $BUILD_OPTION = "release" ]
then
	echo "Building release executable."
elif [ $BUILD_OPTION = "debug" ]
then
	echo "Building debug executable."
else 
	echo "*****************************************************************************"
	echo ""
	echo "     Unknown build option, available options are \"release\" and \"debug\""
	echo ""
	echo "*****************************************************************************"
        exit 1
fi

# Running cmake
if [ $VERB_OPTION = 2 ]
then
  cmake --preset $BUILD_OPTION .. -DCMAKE_FIND_DEBUG_MODE=ON
else
  cmake --preset $BUILD_OPTION ..
fi
# Cleaning possible previous attempts and compiling 
make clean
if [ $VERB_OPTION = 1 ] || [ $VERB_OPTION = 2 ]
then
  make VERBOSE=1
else
  make
fi

if [ -f $EXECUTABLE ]
then
	echo "Executable ctdyn built and created in ${CTDYN_DIR}/${BINARY_DIR}."
else 
	echo "*****************************************************************************"
	echo ""
	echo "  Something went wrong, executable not found in ${CTDYN_DIR}/${BINARY_DIR}."
	echo ""
	echo "*****************************************************************************"
        exit 1
fi

cd $CTDYN_DIR 

echo "************************************************"
echo
echo 'CTDYN installation was successful'
echo
echo "************************************************"
