name: Documentation 

on:
  push:
    branches:
      - main
      - dev 
      - workflow

permissions:
  contents: write

jobs:

  deploy:
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies 
        run: |
          pip install --upgrade pip
          pip install .
          pip install -r ./docs/source/requirements.txt

      - name: Sphinx build 
        run: |
          sphinx-build -b html docs/source docs/_build

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir docs/_build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}

