name: Documentation 

on:
  push:
    branches:
      - main
      - dev 
      - workflow
      - version

permissions:
  contents: write

jobs:

  deploy:
   
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Sphinx build latest 
        uses: .github/workflows/sphinx_build.yml
        with:
          ref: dev
          outdir: latest

      - name: Sphinx build stable 
        uses: .github/workflows/sphinx_build.yml
        with:
          ref: dev
          outdir: stable

      - name: Create HTML index
        env: 
          INDEX_FILE: _build/index.html
        run: |
          echo "<html>" >> ${{ env.INDEX_FILE}}
          echo " <head>" >> ${{ env.INDEX_FILE}}
          echo "   <meta http-equiv=\"refresh\" content=\"0; url=stable/\" />" >> ${{ env.INDEX_FILE}}
          echo " <head>" >> ${{ env.INDEX_FILE}}
          echo "</html>" >> ${{ env.INDEX_FILE}}

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir _build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}

