name: Documentation 

on:
  push:
    branches:
      - main
      - dev 
      - workflow

permissions:
  contents: write

jobs:

  deploy:
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sphinx build 
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/source"
          build-command: "sphinx-build -b html . ../_build"

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir docs/_build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}

