name: Documentation 

on:
  push:
    branches:
      - main
      - dev 
      - workflow
      - version

permissions:
  contents: write

jobs:

  deploy:
   
    runs-on: ubuntu-latest

    steps:

      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies dev 
        run: |
          pip install --upgrade pip
          pip install .
          pip install -r ./docs/source/requirements.txt
          pip install GitPython

      - name: Sphinx build latest 
        run: |
          "update_conf.sh"
          sphinx-build -b html docs/source _build/latest
        shell: bash

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          clean: false

      - name: Install dependencies main 
        run: |
          pip install --upgrade pip
          pip install .
          pip install -r ./docs/source/requirements.txt
          pip install GitPython

      - name: Sphinx build stable 
        run: |
          "update_conf.sh"
          sphinx-build -b html docs/source _build/stable
        shell: bash

      - name: Create HTML index
        env: 
          INDEX_FILE: _build/index.html
        run: |
          echo "<html>" >> ${{ env.INDEX_FILE}}
          echo " <head>" >> ${{ env.INDEX_FILE}}
          echo "   <meta http-equiv=\"refresh\" content=\"0; url=stable/\" />" >> ${{ env.INDEX_FILE}}
          echo " <head>" >> ${{ env.INDEX_FILE}}
          echo "</html>" >> ${{ env.INDEX_FILE}}

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir _build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}

